// lib/jobMatchingRules.ts - 岗位匹配规则库（58个岗位，13大类）

export interface JobMatchingRule {
  id: string;
  category: string;
  jobTitle: string;
  searchKeywords: string[];
  triggers: {
    keywords?: string[];
    courses?: string[];
    activities?: string[];
    praised?: string[];
    helped?: string[];
    selfLearned?: string[];
  };
  matchReasonTemplate: string;
  baseScore: number;
  description: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const JOB_MATCHING_RULES: JobMatchingRule[] = [
  // ========== 技术类（8个） ==========
  {
    id: 'frontend-dev',
    category: '技术类',
    jobTitle: '前端开发实习生',
    searchKeywords: ['前端开发实习生', '前端实习生', 'Web前端'],
    triggers: {
      keywords: ['网站', '网页', '前端', 'JavaScript', 'Vue', 'React', 'HTML', 'CSS', '小程序'],
      selfLearned: ['前端', 'Vue', 'React', 'JavaScript', '网页开发'],
      courses: ['网页设计', 'Web开发', '前端开发'],
      helped: ['做网站', '做网页', '写页面'],
    },
    matchReasonTemplate: '你有前端开发的学习或实践经历',
    baseScore: 80,
    description: '负责网站/小程序的前端页面开发',
    difficulty: 'medium',
  },
  {
    id: 'backend-dev',
    category: '技术类',
    jobTitle: '后端开发实习生',
    searchKeywords: ['后端开发实习生', '后端实习生', 'Java实习生'],
    triggers: {
      keywords: ['后端', '服务器', '数据库', 'Java', 'Python', 'API', '接口'],
      selfLearned: ['后端', 'Java', 'Python', '数据库', '服务器'],
      courses: ['数据库', '软件工程', 'Java程序设计', 'Python'],
      helped: ['写接口', '做后端', '搭服务器'],
    },
    matchReasonTemplate: '你有后端开发相关的学习或实践经历',
    baseScore: 80,
    description: '负责服务器端逻辑和数据库开发',
    difficulty: 'medium',
  },
  {
    id: 'data-analyst',
    category: '技术类',
    jobTitle: '数据分析实习生',
    searchKeywords: ['数据分析实习生', '数据运营实习生', 'BI实习生'],
    triggers: {
      keywords: ['数据', '分析', 'Excel', '表格', '统计', '报表'],
      selfLearned: ['数据分析', 'Excel', 'Python数据分析', 'SQL'],
      courses: ['统计学', '数据分析', 'Excel', '概率论'],
      helped: ['做表格', '统计数据', '分析数据'],
    },
    matchReasonTemplate: '你有数据处理和分析相关的经历',
    baseScore: 75,
    description: '负责数据整理、分析和报表制作',
    difficulty: 'easy',
  },
  {
    id: 'qa-engineer',
    category: '技术类',
    jobTitle: '测试工程师实习生',
    searchKeywords: ['测试工程师实习生', '软件测试实习生', 'QA实习生'],
    triggers: {
      keywords: ['测试', 'Bug', '找问题', '调试'],
      selfLearned: ['软件测试', '自动化测试'],
      courses: ['软件测试', '软件工程'],
      praised: ['细心', '认真', '找问题'],
    },
    matchReasonTemplate: '你细心认真，适合从事测试工作',
    baseScore: 70,
    description: '负责软件功能测试和Bug发现',
    difficulty: 'easy',
  },
  {
    id: 'mobile-dev',
    category: '技术类',
    jobTitle: '移动开发实习生',
    searchKeywords: ['Android开发实习生', 'iOS开发实习生', '移动端开发实习生'],
    triggers: {
      keywords: ['APP', 'Android', 'iOS', '移动端', '小程序', 'Flutter', 'React Native', 'Swift', 'Kotlin'],
      selfLearned: ['Android开发', 'iOS开发', 'Flutter', '移动开发', 'APP开发'],
      courses: ['移动开发', 'Android开发', 'iOS开发', '移动应用开发'],
      helped: ['做APP', '开发小程序', '写移动应用'],
    },
    matchReasonTemplate: '你有移动应用开发相关的学习或实践经历',
    baseScore: 82,
    description: '负责iOS/Android移动应用的开发和维护',
    difficulty: 'hard',
  },
  {
    id: 'algorithm-eng',
    category: '技术类',
    jobTitle: '算法工程师实习生',
    searchKeywords: ['算法工程师实习生', 'AI算法实习生', '机器学习实习生'],
    triggers: {
      keywords: ['算法', '机器学习', '深度学习', 'AI', '神经网络', '模型', '训练'],
      selfLearned: ['机器学习', '深度学习', 'PyTorch', 'TensorFlow', 'AI算法'],
      courses: ['机器学习', '深度学习', '人工智能', '模式识别', '数据挖掘'],
      helped: ['训练模型', '调参', '算法优化'],
    },
    matchReasonTemplate: '你有算法和AI相关的学习研究经历',
    baseScore: 85,
    description: '负责算法模型的设计、训练和优化',
    difficulty: 'hard',
  },
  {
    id: 'devops-eng',
    category: '技术类',
    jobTitle: '运维开发实习生',
    searchKeywords: ['运维工程师实习生', 'DevOps实习生', '运维开发实习生'],
    triggers: {
      keywords: ['Linux', '服务器', '部署', '运维', 'Docker', '容器', 'Shell', '自动化'],
      selfLearned: ['Linux', 'Docker', 'Kubernetes', '运维', 'Shell脚本'],
      courses: ['操作系统', '计算机网络', 'Linux系统管理'],
      helped: ['搭服务器', '部署项目', '配置环境'],
    },
    matchReasonTemplate: '你有服务器运维和部署相关的经历',
    baseScore: 78,
    description: '负责系统部署、运维和自动化流程',
    difficulty: 'medium',
  },
  {
    id: 'embedded-dev',
    category: '技术类',
    jobTitle: '嵌入式开发实习生',
    searchKeywords: ['嵌入式开发实习生', '嵌入式软件实习生', '单片机开发实习生'],
    triggers: {
      keywords: ['嵌入式', '单片机', 'STM32', 'ARM', '硬件', '电路', 'FPGA', '传感器'],
      selfLearned: ['嵌入式开发', '单片机', 'STM32', 'Arduino', '硬件设计'],
      courses: ['嵌入式系统', '单片机原理', '微机原理', '电路分析', '数字电路'],
      helped: ['做嵌入式项目', '写单片机程序', '设计电路'],
    },
    matchReasonTemplate: '你有嵌入式系统和硬件开发的学习经历',
    baseScore: 83,
    description: '负责嵌入式系统的软件开发和调试',
    difficulty: 'hard',
  },

  // ========== 运营类（6个） ==========
  {
    id: 'social-media-ops',
    category: '运营类',
    jobTitle: '新媒体运营实习生',
    searchKeywords: ['新媒体运营实习生', '公众号运营实习生', '内容运营实习生'],
    triggers: {
      keywords: ['公众号', '小红书', '抖音', '自媒体', '推文', '文章', '内容'],
      activities: ['公众号运营', '自媒体', '写文章', '内容创作'],
      selfLearned: ['公众号运营', '自媒体', '写作'],
      helped: ['写推文', '运营公众号', '做内容'],
    },
    matchReasonTemplate: '你有新媒体/内容创作相关经历',
    baseScore: 80,
    description: '负责公众号/小红书等平台的内容运营',
    difficulty: 'easy',
  },
  {
    id: 'community-ops',
    category: '运营类',
    jobTitle: '社群运营实习生',
    searchKeywords: ['社群运营实习生', '用户运营实习生', '社群管理'],
    triggers: {
      keywords: ['社群', '群', '微信群', 'QQ群', '管理群', '社群管理'],
      activities: ['社群运营', '管理群', '班级群管理'],
      praised: ['沟通能力', '组织能力', '协调能力'],
      helped: ['管理群', '组织群活动'],
    },
    matchReasonTemplate: '你有社群管理或组织协调的经历',
    baseScore: 75,
    description: '负责社群维护、用户互动和活动组织',
    difficulty: 'easy',
  },
  {
    id: 'event-ops',
    category: '运营类',
    jobTitle: '活动运营实习生',
    searchKeywords: ['活动运营实习生', '活动策划实习生', '活动执行实习生'],
    triggers: {
      keywords: ['活动', '策划', '组织活动', '执行活动', '线下活动'],
      activities: ['学生会活动', '社团活动', '班级活动', '活动策划', '活动组织'],
      praised: ['组织能力', '执行力', '策划能力'],
    },
    matchReasonTemplate: '你有活动策划和组织的经历',
    baseScore: 75,
    description: '负责线上/线下活动的策划和执行',
    difficulty: 'easy',
  },
  {
    id: 'user-ops',
    category: '运营类',
    jobTitle: '用户运营实习生',
    searchKeywords: ['用户运营实习生', '用户增长实习生', '用户维护实习生'],
    triggers: {
      keywords: ['用户', '粉丝', '会员', '活跃度', '留存', '反馈', '满意度'],
      activities: ['用户维护', '粉丝互动', '会员管理', '用户调研'],
      praised: ['沟通能力', '服务意识', '耐心', '亲和力'],
      helped: ['解决用户问题', '处理用户反馈', '用户咨询'],
    },
    matchReasonTemplate: '你有用户服务和维护的经历',
    baseScore: 73,
    description: '负责用户关系维护、活跃度提升和用户问题处理',
    difficulty: 'easy',
  },
  {
    id: 'product-ops',
    category: '运营类',
    jobTitle: '产品运营实习生',
    searchKeywords: ['产品运营实习生', '产品助理实习生', '产品支持实习生'],
    triggers: {
      keywords: ['产品', '功能', '用户需求', '产品优化', '用户调研', '竞品分析'],
      activities: ['产品设计', '用户调研', '竞品分析', '功能优化'],
      selfLearned: ['产品经理', '产品设计', '用户研究', 'Axure', 'Figma'],
      praised: ['逻辑思维', '用户洞察', '分析能力'],
    },
    matchReasonTemplate: '你有产品思维或用户研究的经历',
    baseScore: 76,
    description: '协助产品功能优化、用户调研和数据分析',
    difficulty: 'medium',
  },
  {
    id: 'growth-ops',
    category: '运营类',
    jobTitle: '增长运营实习生',
    searchKeywords: ['增长运营实习生', '用户增长实习生', '增长黑客实习生'],
    triggers: {
      keywords: ['增长', '拉新', '转化', '裂变', '获客', '数据驱动', 'A/B测试'],
      activities: ['用户增长', '裂变活动', '获客推广', '数据分析'],
      praised: ['数据敏感', '创新思维', '执行力'],
      selfLearned: ['增长黑客', '数据分析', '用户增长'],
    },
    matchReasonTemplate: '你有用户增长或数据驱动的经历',
    baseScore: 75,
    description: '负责用户增长策略的制定和执行',
    difficulty: 'medium',
  },

  // ========== 市场类（5个） ==========
  {
    id: 'marketing',
    category: '市场类',
    jobTitle: '市场推广实习生',
    searchKeywords: ['市场推广实习生', '市场助理实习生', '营销实习生'],
    triggers: {
      keywords: ['推广', '营销', '宣传', '市场', '拉新'],
      activities: ['外联', '赞助', '推广', '宣传', '拉新'],
      praised: ['沟通能力', '表达能力', '说服能力'],
    },
    matchReasonTemplate: '你有推广或市场相关的经历',
    baseScore: 70,
    description: '负责产品/活动的推广和宣传',
    difficulty: 'easy',
  },
  {
    id: 'bd',
    category: '市场类',
    jobTitle: '商务拓展实习生',
    searchKeywords: ['商务拓展实习生', 'BD实习生', '商务助理实习生'],
    triggers: {
      keywords: ['商务', '合作', '谈判', '对接', '客户'],
      activities: ['外联', '赞助', '谈合作', '对接商家'],
      praised: ['沟通能力', '谈判能力', '外向'],
    },
    matchReasonTemplate: '你有商务沟通或对外联络的经历',
    baseScore: 70,
    description: '负责商务合作洽谈和客户维护',
    difficulty: 'medium',
  },
  {
    id: 'brand',
    category: '市场类',
    jobTitle: '品牌营销实习生',
    searchKeywords: ['品牌营销实习生', '品牌策划实习生', '品牌推广实习生'],
    triggers: {
      keywords: ['品牌', '传播', '策划', '创意', 'Slogan', '品牌形象', '品牌故事'],
      activities: ['品牌策划', '创意设计', '传播方案', '品牌故事撰写'],
      selfLearned: ['品牌营销', '广告策划', '创意写作'],
      praised: ['创意能力', '文案能力', '审美'],
    },
    matchReasonTemplate: '你有品牌传播或创意策划的经历',
    baseScore: 74,
    description: '负责品牌传播策划和创意内容产出',
    difficulty: 'medium',
  },
  {
    id: 'event-marketing',
    category: '市场类',
    jobTitle: '活动营销实习生',
    searchKeywords: ['活动营销实习生', '线下活动实习生', '活动执行实习生'],
    triggers: {
      keywords: ['活动营销', '线下', '路演', '展会', '活动执行'],
      activities: ['活动营销', '线下推广', '路演', '展会'],
      praised: ['执行力', '组织能力', '外向'],
    },
    matchReasonTemplate: '你有活动营销或线下执行的经历',
    baseScore: 72,
    description: '负责线下营销活动的策划和执行',
    difficulty: 'easy',
  },
  {
    id: 'pr',
    category: '市场类',
    jobTitle: '公关实习生',
    searchKeywords: ['公关实习生', 'PR实习生', '媒介实习生'],
    triggers: {
      keywords: ['公关', '媒体', '传播', '稿件', '新闻', '发布会', '舆情'],
      activities: ['媒体对接', '新闻稿撰写', '发布会组织', '舆情监测'],
      selfLearned: ['公关传播', '新闻写作', '媒体关系'],
      praised: ['沟通能力', '写作能力', '应变能力'],
    },
    matchReasonTemplate: '你有公关传播或媒体相关的经历',
    baseScore: 72,
    description: '负责媒体关系维护和公关传播执行',
    difficulty: 'hard',
  },

  // ========== 设计类（5个） ==========
  {
    id: 'graphic-design',
    category: '设计类',
    jobTitle: '平面设计实习生',
    searchKeywords: ['平面设计实习生', '美工实习生', '视觉设计实习生'],
    triggers: {
      keywords: ['设计', '海报', 'PS', '修图', '作图', '排版'],
      selfLearned: ['Photoshop', 'PS', 'AI', '平面设计', '海报设计'],
      activities: ['设计海报', '做海报', '宣传物料设计'],
      helped: ['做海报', '设计', 'P图'],
    },
    matchReasonTemplate: '你有平面设计相关的技能或经历',
    baseScore: 80,
    description: '负责海报、宣传物料等平面设计',
    difficulty: 'easy',
  },
  {
    id: 'ui-design',
    category: '设计类',
    jobTitle: 'UI设计实习生',
    searchKeywords: ['UI设计实习生', '界面设计实习生', '交互设计实习生'],
    triggers: {
      keywords: ['UI', '界面', '交互', '原型', 'Figma', 'Sketch', '设计规范'],
      selfLearned: ['UI设计', 'Figma', 'Sketch', '交互设计', '原型设计'],
      activities: ['界面设计', '原型制作', '设计规范'],
      helped: ['设计界面', '做原型', '设计APP页面'],
    },
    matchReasonTemplate: '你有UI界面设计相关的技能或经历',
    baseScore: 80,
    description: '负责产品界面设计和交互原型制作',
    difficulty: 'medium',
  },
  {
    id: 'video-editor',
    category: '设计类',
    jobTitle: '视频剪辑实习生',
    searchKeywords: ['视频剪辑实习生', '短视频运营实习生', '后期实习生'],
    triggers: {
      keywords: ['视频', '剪辑', '短视频', '抖音', 'B站', '剪辑软件'],
      selfLearned: ['视频剪辑', 'Premiere', '剪映', 'Final Cut', '短视频'],
      activities: ['拍视频', '剪视频', '短视频创作'],
      helped: ['剪视频', '做视频'],
    },
    matchReasonTemplate: '你有视频剪辑相关的技能或经历',
    baseScore: 80,
    description: '负责短视频的拍摄和后期剪辑',
    difficulty: 'easy',
  },
  {
    id: 'motion-design',
    category: '设计类',
    jobTitle: '动效设计实习生',
    searchKeywords: ['动效设计实习生', '动画设计实习生', 'AE实习生'],
    triggers: {
      keywords: ['动效', '动画', 'AE', 'After Effects', 'C4D', '特效', 'MG动画'],
      selfLearned: ['After Effects', 'AE', 'C4D', '动效设计', '动画制作'],
      activities: ['动效制作', '动画设计', '特效制作'],
      helped: ['做动画', '做动效', '做特效'],
    },
    matchReasonTemplate: '你有动效设计相关的学习或实践经历',
    baseScore: 82,
    description: '负责视频动效和交互动效的设计制作',
    difficulty: 'hard',
  },
  {
    id: '3d-design',
    category: '设计类',
    jobTitle: '3D设计实习生',
    searchKeywords: ['3D设计实习生', '3D建模实习生', '三维设计实习生'],
    triggers: {
      keywords: ['3D', '建模', 'Blender', 'C4D', '三维', '渲染', 'Maya'],
      selfLearned: ['3D建模', 'Blender', 'C4D', 'Maya', '三维设计'],
      courses: ['3D建模', '计算机图形学', '数字媒体'],
      helped: ['做3D模型', '做三维动画'],
    },
    matchReasonTemplate: '你有3D建模设计相关的学习经历',
    baseScore: 82,
    description: '负责3D建模和视觉效果制作',
    difficulty: 'hard',
  },

  // ========== 客服/支持类（4个） ==========
  {
    id: 'customer-service',
    category: '客服/支持类',
    jobTitle: '客服实习生',
    searchKeywords: ['客服实习生', '客户服务实习生', '在线客服'],
    triggers: {
      keywords: ['客服', '服务', '解答', '回复', '咨询'],
      helped: ['答疑', '解答问题', '回复消息', '处理投诉'],
      praised: ['耐心', '细心', '服务意识', '沟通能力'],
    },
    matchReasonTemplate: '你有耐心服务他人、解答问题的经历',
    baseScore: 70,
    description: '负责客户咨询解答和服务支持',
    difficulty: 'easy',
  },
  {
    id: 'user-support',
    category: '客服/支持类',
    jobTitle: '用户支持实习生',
    searchKeywords: ['用户运营实习生', '用户服务实习生', '客户成功实习生'],
    triggers: {
      keywords: ['用户', '反馈', '满意度', '维护用户', '用户问题'],
      activities: ['用户维护', '社群管理', '用户服务'],
      praised: ['沟通能力', '服务意识', '耐心'],
      helped: ['解决用户问题', '处理用户反馈'],
    },
    matchReasonTemplate: '你有用户服务和问题解决的经历',
    baseScore: 72,
    description: '负责用户问题处理和满意度维护',
    difficulty: 'easy',
  },
  {
    id: 'tech-support',
    category: '客服/支持类',
    jobTitle: '技术支持实习生',
    searchKeywords: ['技术支持实习生', 'IT支持实习生', '运维支持实习生'],
    triggers: {
      keywords: ['技术支持', 'IT', '运维', '电脑问题', '技术问题'],
      helped: ['修电脑', '解决技术问题', 'IT支持', '装软件', '网络问题'],
      selfLearned: ['电脑维修', '网络维护', 'IT技术'],
    },
    matchReasonTemplate: '你有IT/技术问题解决的经历',
    baseScore: 75,
    description: '负责技术问题解答和系统维护支持',
    difficulty: 'easy',
  },
  {
    id: 'sales-support',
    category: '客服/支持类',
    jobTitle: '销售支持实习生',
    searchKeywords: ['销售支持实习生', '销售助理实习生', '商务助理实习生'],
    triggers: {
      keywords: ['销售支持', '销售助理', '跟进', '客户', '合同', '报价'],
      activities: ['销售支持', '客户跟进', '合同管理'],
      praised: ['细心', '沟通能力', '执行力'],
      helped: ['做报价', '跟进客户', '处理订单'],
    },
    matchReasonTemplate: '你有销售支持或行政辅助的经历',
    baseScore: 70,
    description: '协助销售团队处理日常事务和客户跟进',
    difficulty: 'easy',
  },

  // ========== 行政/助理类（6个） ==========
  {
    id: 'admin-assistant',
    category: '行政/助理类',
    jobTitle: '行政助理实习生',
    searchKeywords: ['行政助理实习生', '行政实习生', '文员实习生'],
    triggers: {
      keywords: ['行政', '文员', '文档', '表格', 'Excel', '整理', '归档'],
      activities: ['学生会行政', '班级管理', '文档整理'],
      praised: ['细心', '认真', '负责', '执行力'],
      helped: ['整理文档', '做表格', '处理文件'],
    },
    matchReasonTemplate: '你细心负责，适合行政支持类工作',
    baseScore: 70,
    description: '负责日常行政事务和文档处理',
    difficulty: 'easy',
  },
  {
    id: 'hr-assistant',
    category: '行政/助理类',
    jobTitle: '人事助理实习生',
    searchKeywords: ['人事助理实习生', 'HR实习生', '招聘助理实习生'],
    triggers: {
      keywords: ['人事', 'HR', '招聘', '面试', '简历'],
      activities: ['学生会人事', '社团招新', '组织面试'],
      praised: ['细心', '沟通能力', '组织能力'],
    },
    matchReasonTemplate: '你有招聘或人事相关的经历',
    baseScore: 70,
    description: '协助招聘、入职等人事工作',
    difficulty: 'easy',
  },
  {
    id: 'project-assistant',
    category: '行政/助理类',
    jobTitle: '项目助理实习生',
    searchKeywords: ['项目助理实习生', '项目协调实习生', 'PMO实习生'],
    triggers: {
      keywords: ['项目', '进度', '协调', '跟进', '汇报'],
      activities: ['项目管理', '活动统筹', '项目协调'],
      praised: ['组织能力', '协调能力', '执行力'],
    },
    matchReasonTemplate: '你有项目协调和跟进的经历',
    baseScore: 72,
    description: '协助项目进度跟进和协调沟通',
    difficulty: 'medium',
  },
  {
    id: 'ceo-assistant',
    category: '行政/助理类',
    jobTitle: '总经理助理实习生',
    searchKeywords: ['总经理助理实习生', '总裁助理实习生', '总助实习生'],
    triggers: {
      keywords: ['总助', '总经理', '汇报', '会议', '日程', '行程'],
      activities: ['综合事务', '会议组织', '行程安排'],
      praised: ['细心', '沟通能力', '协调能力', '综合素质'],
    },
    matchReasonTemplate: '你有综合协调和汇报的经历',
    baseScore: 74,
    description: '协助总经理处理日常事务和沟通协调',
    difficulty: 'hard',
  },
  {
    id: 'finance-assistant',
    category: '行政/助理类',
    jobTitle: '财务助理实习生',
    searchKeywords: ['财务助理实习生', '会计实习生', '出纳实习生'],
    triggers: {
      keywords: ['财务', '会计', '报销', '发票', '账务', 'Excel', '报销流程'],
      selfLearned: ['会计', '财务', 'Excel函数', '财务软件'],
      courses: ['会计学', '财务管理', '成本会计', '审计学'],
      praised: ['细心', '数字敏感', '认真负责'],
      helped: ['做报销', '整理发票', '处理账务'],
    },
    matchReasonTemplate: '你有财务或数据处理相关的经历',
    baseScore: 72,
    description: '协助日常财务处理和报销审核',
    difficulty: 'medium',
  },
  {
    id: 'legal-assistant',
    category: '行政/助理类',
    jobTitle: '法务助理实习生',
    searchKeywords: ['法务助理实习生', '法律实习生', '法务实习生'],
    triggers: {
      keywords: ['法律', '合同', '法规', '审核', '文书', '合规', '法务'],
      selfLearned: ['法律', '合同审核', '法律文书'],
      courses: ['法学', '经济法', '合同法', '公司法'],
      praised: ['逻辑思维', '文字能力', '细心'],
    },
    matchReasonTemplate: '你有法律或文书审核相关的学习经历',
    baseScore: 75,
    description: '协助合同审核和法务文书处理',
    difficulty: 'hard',
  },

  // ========== 销售类（4个） ==========
  {
    id: 'sales',
    category: '销售类',
    jobTitle: '销售实习生',
    searchKeywords: ['销售实习生', '销售代表实习生', '业务员实习生'],
    triggers: {
      keywords: ['销售', '推销', '卖', '业绩', '客户'],
      activities: ['兼职销售', '地推', '促销', '推销'],
      praised: ['沟通能力', '外向', '抗压能力', '目标感'],
    },
    matchReasonTemplate: '你有销售或客户沟通的经历',
    baseScore: 68,
    description: '负责产品销售和客户开发',
    difficulty: 'medium',
  },
  {
    id: 'field-sales',
    category: '销售类',
    jobTitle: '地推实习生',
    searchKeywords: ['地推实习生', '推广实习生', '市场拓展实习生'],
    triggers: {
      keywords: ['地推', '推广', '线下', '扫楼', '发传单'],
      activities: ['地推', '发传单', '线下推广', '扫楼'],
      praised: ['吃苦耐劳', '执行力', '外向'],
    },
    matchReasonTemplate: '你有线下推广或地推的经历',
    baseScore: 65,
    description: '负责线下市场推广和用户拓展',
    difficulty: 'easy',
  },
  {
    id: 'inside-sales',
    category: '销售类',
    jobTitle: '电话销售实习生',
    searchKeywords: ['电话销售实习生', '电销实习生', '电话客服实习生'],
    triggers: {
      keywords: ['电话', '沟通', '外向', '抗压', '说服', '表达', '目标感'],
      activities: ['电话客服', '电话销售', '电话调研'],
      praised: ['沟通能力', '表达能力', '抗压能力', '外向'],
      helped: ['电话沟通', '电话回访'],
    },
    matchReasonTemplate: '你有电话沟通或客户联络的经历',
    baseScore: 68,
    description: '负责电话客户开发和产品推广',
    difficulty: 'easy',
  },
  {
    id: 'sales-coordinator',
    category: '销售类',
    jobTitle: '销售协调实习生',
    searchKeywords: ['销售协调实习生', '销售内勤实习生', '商务协调实习生'],
    triggers: {
      keywords: ['协调', '跟进', '文档', '合同', '报价', '订单'],
      activities: ['销售支持', '订单跟进', '合同管理'],
      praised: ['细心', '执行力', '协调能力'],
    },
    matchReasonTemplate: '你有销售支持或协调的经历',
    baseScore: 70,
    description: '协助销售团队协调订单和客户跟进',
    difficulty: 'easy',
  },

  // ========== 内容类（5个） ==========
  {
    id: 'copywriting',
    category: '内容类',
    jobTitle: '文案策划实习生',
    searchKeywords: ['文案策划实习生', '文案实习生', '策划实习生'],
    triggers: {
      keywords: ['文案', '策划', '写', '文章', '标题', '创意'],
      activities: ['写文章', '文案创作', '内容策划'],
      selfLearned: ['写作', '文案', '创意'],
      praised: ['写作能力', '创意能力', '表达能力'],
    },
    matchReasonTemplate: '你有文案写作或内容策划的经历',
    baseScore: 75,
    description: '负责广告文案、宣传内容撰写',
    difficulty: 'easy',
  },
  {
    id: 'content-editor',
    category: '内容类',
    jobTitle: '新媒体编辑实习生',
    searchKeywords: ['新媒体编辑实习生', '内容编辑实习生', '编辑实习生'],
    triggers: {
      keywords: ['编辑', '排版', '审核', '内容', '选题'],
      activities: ['编辑', '排版', '内容审核', '选题策划'],
      praised: ['细心', '文字能力', '审美'],
    },
    matchReasonTemplate: '你有内容编辑或排版相关的经历',
    baseScore: 72,
    description: '负责内容编辑、审核和排版',
    difficulty: 'easy',
  },
  {
    id: 'video-content',
    category: '内容类',
    jobTitle: '短视频编导实习生',
    searchKeywords: ['短视频编导实习生', '视频策划实习生', '内容编导实习生'],
    triggers: {
      keywords: ['短视频', '抖音', 'B站', '脚本', '编导', '拍摄', '创意', '选题'],
      selfLearned: ['短视频创作', '视频编导', '脚本写作', '拍摄剪辑'],
      activities: ['短视频创作', '账号运营', '视频策划', '内容创作'],
      helped: ['拍视频', '写脚本', '做短视频'],
    },
    matchReasonTemplate: '你有短视频创作或编导的经历',
    baseScore: 78,
    description: '负责短视频选题策划、脚本创作和拍摄指导',
    difficulty: 'medium',
  },
  {
    id: 'scriptwriter',
    category: '内容类',
    jobTitle: '脚本策划实习生',
    searchKeywords: ['脚本策划实习生', '编剧实习生', '内容策划实习生'],
    triggers: {
      keywords: ['脚本', '编剧', '故事', '剧本', '创意', '叙事'],
      selfLearned: ['脚本写作', '编剧', '创意写作', '故事创作'],
      activities: ['写剧本', '脚本策划', '内容创作'],
      praised: ['创意能力', '写作能力', '想象力'],
    },
    matchReasonTemplate: '你有脚本创作或故事策划的经历',
    baseScore: 76,
    description: '负责视频/活动脚本的策划和撰写',
    difficulty: 'medium',
  },
  {
    id: 'translator',
    category: '内容类',
    jobTitle: '翻译实习生',
    searchKeywords: ['翻译实习生', '英语翻译实习生', '笔译实习生'],
    triggers: {
      keywords: ['翻译', '英语', '外语', '日语', '韩语', '语言', '笔译', '口译'],
      selfLearned: ['英语', '日语', '韩语', '翻译', '外语'],
      courses: ['英语', '翻译', '外语', '语言学'],
      praised: ['语言能力', '文字能力', '细心'],
      helped: ['翻译', '语言辅导', '外语答疑'],
    },
    matchReasonTemplate: '你有外语翻译或语言相关的经历',
    baseScore: 76,
    description: '负责文档翻译和语言本地化支持',
    difficulty: 'medium',
  },

  // ========== 产品类（3个） ==========
  {
    id: 'product-intern',
    category: '产品类',
    jobTitle: '产品助理实习生',
    searchKeywords: ['产品助理实习生', '产品实习生', '产品策划实习生'],
    triggers: {
      keywords: ['产品', '需求', '原型', '用户', '功能', '竞品', 'Axure', 'Figma', 'PRD'],
      selfLearned: ['产品经理', '产品设计', 'Axure', 'Figma', '用户研究'],
      activities: ['产品设计', '需求分析', '竞品分析', '原型设计'],
      courses: ['产品设计', '用户体验', '人机交互'],
      praised: ['逻辑思维', '用户洞察', '分析能力'],
    },
    matchReasonTemplate: '你有产品设计或用户研究的经历',
    baseScore: 78,
    description: '协助产品需求分析、原型设计和用户调研',
    difficulty: 'medium',
  },
  {
    id: 'product-ops-intern',
    category: '产品类',
    jobTitle: '产品运营实习生',
    searchKeywords: ['产品运营实习生', '产品数据分析实习生'],
    triggers: {
      keywords: ['产品运营', '数据分析', '用户行为', '功能优化', '版本'],
      activities: ['产品运营', '数据分析', '用户行为分析'],
      praised: ['数据敏感', '逻辑思维', '分析能力'],
    },
    matchReasonTemplate: '你有产品运营或数据驱动的经历',
    baseScore: 76,
    description: '负责产品数据分析和功能优化建议',
    difficulty: 'medium',
  },
  {
    id: 'ux-researcher',
    category: '产品类',
    jobTitle: '用户研究实习生',
    searchKeywords: ['用户研究实习生', 'UX研究实习生', '用户调研实习生'],
    triggers: {
      keywords: ['用户研究', '调研', '访谈', '问卷', '用户体验', '可用性测试', '用户画像'],
      selfLearned: ['用户研究', 'UX设计', '问卷设计', '数据分析'],
      activities: ['用户调研', '问卷设计', '用户访谈', '可用性测试'],
      courses: ['用户体验', '心理学', '社会学', '市场调研'],
      praised: ['洞察力', '分析能力', '沟通能力'],
    },
    matchReasonTemplate: '你有用户研究或调研分析的经历',
    baseScore: 80,
    description: '负责用户调研、访谈和数据分析',
    difficulty: 'hard',
  },

  // ========== 电商类（4个） ==========
  {
    id: 'e-commerce-ops',
    category: '电商类',
    jobTitle: '电商运营实习生',
    searchKeywords: ['电商运营实习生', '淘宝运营实习生', '店铺运营实习生'],
    triggers: {
      keywords: ['电商', '淘宝', '天猫', '京东', '拼多多', '店铺', '商品', '客服', '订单'],
      selfLearned: ['电商运营', '淘宝开店', '网店运营'],
      activities: ['电商运营', '店铺管理', '商品上架', '客服'],
      helped: ['运营网店', '做电商客服', '处理订单'],
    },
    matchReasonTemplate: '你有电商或店铺运营的经历',
    baseScore: 75,
    description: '负责电商平台店铺运营和商品管理',
    difficulty: 'easy',
  },
  {
    id: 'live-stream-ops',
    category: '电商类',
    jobTitle: '直播运营实习生',
    searchKeywords: ['直播运营实习生', '直播助理实习生', '直播策划实习生'],
    triggers: {
      keywords: ['直播', '主播', '场控', '脚本', '抖音直播', '淘宝直播', '直播间'],
      selfLearned: ['直播运营', '直播策划', '场控'],
      activities: ['直播策划', '直播场控', '主播助理', '直播脚本'],
      praised: ['沟通能力', '应变能力', '执行力'],
    },
    matchReasonTemplate: '你有直播策划或运营的经历',
    baseScore: 76,
    description: '负责直播间策划、场控和主播支持',
    difficulty: 'medium',
  },
  {
    id: 'e-commerce-design',
    category: '电商类',
    jobTitle: '电商设计实习生',
    searchKeywords: ['电商设计实习生', '美工设计实习生', '详情页设计实习生'],
    triggers: {
      keywords: ['电商', '详情页', '主图', '设计', '产品图', 'Banner'],
      selfLearned: ['电商设计', '详情页设计', '产品图设计'],
      activities: ['电商设计', '详情页制作', '产品图设计'],
      helped: ['做详情页', '设计产品图'],
    },
    matchReasonTemplate: '你有电商视觉设计相关的经历',
    baseScore: 78,
    description: '负责电商产品图和详情页设计',
    difficulty: 'easy',
  },
  {
    id: 'supply-chain',
    category: '电商类',
    jobTitle: '供应链实习生',
    searchKeywords: ['供应链实习生', '采购实习生', '物流实习生'],
    triggers: {
      keywords: ['供应链', '采购', '库存', '物流', '仓储', '供应商'],
      selfLearned: ['供应链管理', '采购管理', '物流管理'],
      courses: ['供应链管理', '物流管理', '采购管理'],
      praised: ['细心', '沟通能力', '执行力'],
    },
    matchReasonTemplate: '你有供应链或采购相关的经历',
    baseScore: 72,
    description: '协助供应链管理和采购流程优化',
    difficulty: 'medium',
  },

  // ========== 金融类（4个） ==========
  {
    id: 'financial-intern',
    category: '金融类',
    jobTitle: '金融助理实习生',
    searchKeywords: ['金融实习生', '金融助理实习生', '投资助理实习生'],
    triggers: {
      keywords: ['金融', '投资', '证券', '股票', '基金', '分析', '报告', '研究'],
      selfLearned: ['投资分析', '金融建模', '证券分析'],
      courses: ['金融学', '投资学', '证券投资', '公司金融', '金融市场'],
      praised: ['分析能力', '数字敏感', '逻辑思维'],
    },
    matchReasonTemplate: '你有金融分析或投资研究的经历',
    baseScore: 78,
    description: '协助金融数据分析和投资研究',
    difficulty: 'hard',
  },
  {
    id: 'accounting-intern',
    category: '金融类',
    jobTitle: '会计实习生',
    searchKeywords: ['会计实习生', '财务实习生', '记账实习生'],
    triggers: {
      keywords: ['会计', '凭证', '报表', '记账', '财务', '税务'],
      selfLearned: ['会计', '财务软件', '税务'],
      courses: ['会计学', '财务会计', '税法', '成本会计'],
      praised: ['细心', '数字敏感', '认真'],
    },
    matchReasonTemplate: '你有会计或财务处理的经历',
    baseScore: 74,
    description: '协助日常账务处理和财务报表编制',
    difficulty: 'medium',
  },
  {
    id: 'audit-intern',
    category: '金融类',
    jobTitle: '审计实习生',
    searchKeywords: ['审计实习生', '审计助理实习生', '内审实习生'],
    triggers: {
      keywords: ['审计', '核查', '内控', '合规', '风险'],
      selfLearned: ['审计', '内控', '风险管理'],
      courses: ['审计学', '内部控制', '风险管理'],
      praised: ['细心', '逻辑思维', '严谨'],
    },
    matchReasonTemplate: '你有审计或财务核查的学习经历',
    baseScore: 76,
    description: '协助审计项目执行和底稿编制',
    difficulty: 'hard',
  },
  {
    id: 'investment-intern',
    category: '金融类',
    jobTitle: '投资分析实习生',
    searchKeywords: ['投资分析实习生', '行研实习生', '行业研究实习生'],
    triggers: {
      keywords: ['投资', '分析', '行业研究', '报告', '尽调', '估值'],
      selfLearned: ['行业研究', '投资分析', '财务建模'],
      courses: ['投资学', '公司金融', '财务分析'],
      praised: ['分析能力', '研究能力', '逻辑思维'],
    },
    matchReasonTemplate: '你有投资分析或行业研究的经历',
    baseScore: 78,
    description: '负责行业研究和投资分析报告撰写',
    difficulty: 'hard',
  },

  // ========== 教育类（3个） ==========
  {
    id: 'teaching-assistant',
    category: '教育类',
    jobTitle: '助教实习生',
    searchKeywords: ['助教实习生', '教学助理实习生', '辅导老师实习生'],
    triggers: {
      keywords: ['辅导', '答疑', '教学', '学生', '老师', '课程', '讲解', '备课'],
      activities: ['助教', '辅导', '答疑', '家教', '课后辅导'],
      helped: ['辅导作业', '答疑解惑', '讲解题目', '家教'],
      praised: ['耐心', '表达能力', '责任心'],
    },
    matchReasonTemplate: '你有辅导或教学相关的经历',
    baseScore: 72,
    description: '协助课程教学和学生答疑辅导',
    difficulty: 'easy',
  },
  {
    id: 'education-ops',
    category: '教育类',
    jobTitle: '教育运营实习生',
    searchKeywords: ['教育运营实习生', '课程运营实习生', '教育社群实习生'],
    triggers: {
      keywords: ['教育', '课程', '社群', '学员', '学习'],
      activities: ['教育运营', '课程运营', '学员管理', '社群管理'],
      praised: ['沟通能力', '服务意识', '组织能力'],
    },
    matchReasonTemplate: '你有教育行业或课程运营的经历',
    baseScore: 74,
    description: '负责教育产品运营和学员服务',
    difficulty: 'easy',
  },
  {
    id: 'curriculum-design',
    category: '教育类',
    jobTitle: '课程策划实习生',
    searchKeywords: ['课程策划实习生', '教研实习生', '课程设计实习生'],
    triggers: {
      keywords: ['课程', '教案', '教学设计', '教研', '课件', '知识点'],
      selfLearned: ['课程设计', '教学设计', '教案编写'],
      activities: ['课程策划', '教案设计', '课件制作'],
      praised: ['逻辑思维', '表达能力', '创意'],
    },
    matchReasonTemplate: '你有课程设计或教案策划的经历',
    baseScore: 76,
    description: '负责课程内容策划和教学方案设计',
    difficulty: 'medium',
  },

  // ========== 游戏类（3个） ==========
  {
    id: 'game-ops',
    category: '游戏类',
    jobTitle: '游戏运营实习生',
    searchKeywords: ['游戏运营实习生', '游戏社区实习生', '游戏策划实习生'],
    triggers: {
      keywords: ['游戏', '玩家', '公会', '活动', '社区', '论坛', '攻略', '版本'],
      activities: ['游戏公会管理', '游戏活动策划', '游戏社区运营', '攻略撰写'],
      praised: ['热爱游戏', '沟通能力', '组织能力'],
      helped: ['组织游戏活动', '管理游戏社群'],
    },
    matchReasonTemplate: '你有游戏运营或社区管理的经历',
    baseScore: 74,
    description: '负责游戏活动策划和玩家社区运营',
    difficulty: 'medium',
  },
  {
    id: 'game-tester',
    category: '游戏类',
    jobTitle: '游戏测试实习生',
    searchKeywords: ['游戏测试实习生', '游戏QA实习生', '游戏体验实习生'],
    triggers: {
      keywords: ['游戏', '测试', 'Bug', '体验', '手游', '端游', '网游', '游戏玩家'],
      selfLearned: ['游戏测试', '游戏开发', 'Unity', '游戏设计'],
      activities: ['游戏公会', '游戏活动', '游戏测试'],
      praised: ['细心', '热爱游戏', '找问题'],
      helped: ['测试游戏', '找Bug', '游戏问题反馈'],
    },
    matchReasonTemplate: '你热爱游戏，细心认真，适合游戏测试工作',
    baseScore: 70,
    description: '负责游戏功能测试和Bug发现',
    difficulty: 'easy',
  },
  {
    id: 'game-designer',
    category: '游戏类',
    jobTitle: '游戏策划实习生',
    searchKeywords: ['游戏策划实习生', '游戏设计实习生', '玩法策划实习生'],
    triggers: {
      keywords: ['游戏策划', '玩法', '系统设计', '数值', '关卡', '游戏设计'],
      selfLearned: ['游戏策划', '游戏设计', '关卡设计', '数值策划'],
      activities: ['游戏策划', '玩法设计', '系统设计'],
      praised: ['创意能力', '逻辑思维', '热爱游戏'],
    },
    matchReasonTemplate: '你有游戏策划或玩法设计的经历',
    baseScore: 78,
    description: '负责游戏玩法和系统设计',
    difficulty: 'hard',
  },
];

export default JOB_MATCHING_RULES;
